Data Science Homework 2
================
2022-10-04

Hemangi Modi (UNI: hbm2126)

# Problem 1

``` r
subway_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c"), show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  select(line:entry, vending, ada) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

### Describing the dataset and cleaning process

The subway_df dataset contains various variables that pertain to the NYC
transit information. Some of the variables include the subway line, the
station name, the different routes that the line serves, the type of
entrance to the subway station (stair, elevator, etc), whether there is
entrance allowed through vending or not, and if the station is ADA
compliant, among others. So far, the data cleaning steps entailed
cleaning the variable name, selecting a few key columns to analyze the
data and converted the entry variable from a character to a logical
variable. There are 1868 rows and 19 columns. The data is not entirely
tidy because it is not compact in terms of route and route names.

### Answering questions using subway dataset

``` r
subway_df %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

There are 465 distinct stations.

``` r
subway_df %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

84 stations are ADA compliant.

``` r
subway_df %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

About 37.7% of station entrances/exits without vending allow entrance.

``` r
subway_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
subway_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

60 distinct stations serve the A train. Of these 60 stations, 17 are ADA
compliant.

``` r
View(subway_df)
```

# Problem 2

``` r
mr_trash_wheel_df= 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>%
  select(dumpster:homes_powered) %>%
  drop_na(dumpster) %>% 
  mutate(what_sheet = "Mr Trash Wheel") %>% 
  mutate(sports_balls = as.integer(round(sports_balls,0)))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof_trash_wheel_df= 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>%
  mutate(what_sheet = "Prof Trash Wheel") %>% 
  drop_na(dumpster)
```

``` r
prof_trash_wheel_df$year = as.character(prof_trash_wheel_df$year)
```

``` r
combined_trash_df = bind_rows(mr_trash_wheel_df, prof_trash_wheel_df)
```

``` r
combined_trash_df %>% 
  filter(what_sheet == "Prof Trash Wheel") %>% 
  summarise(total_weight = sum(weight_tons))
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         190.

``` r
combined_trash_df %>% 
  filter(what_sheet == "Mr Trash Wheel" & year == 2020) %>% 
  summarise(total_sports_balls = sum(sports_balls))
```

    ## # A tibble: 1 × 1
    ##   total_sports_balls
    ##                <int>
    ## 1                856

### Overall description and answers to specific questions

This dataset has information about trash that was collected at different
locations and sites by Mr. Trash Wheel and Professor Trash Wheel. The
dataset has 15 columns and 641 rows. This combined dataset contains
information on the weight of trash collected on a certain day and also
contains details about the type of trash - plastic bottles, cigarette
butts, glass bottles, etc. The total weight of trash collected by
Professor Trash Wheel was 190.12 tons. Mr. Trash Wheel collected a total
of 856 sports balls in 2020.

# Problem 3

``` r
pols_df = 
  read_csv("data/fivethirtyeight_datasets/pols-month.csv", show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-")%>%
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day), 
    month = month.abb[month], 
    president = case_when(prez_gop == 1 ~ "gop", prez_dem == 1 ~ "dem")) %>% 
  subset(select = -c(day, prez_gop, prez_dem ))
```

``` r
snp_df = 
  read_csv("data/fivethirtyeight_datasets/snp.csv", show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/")%>%
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    month = month.abb[month],
    year = as.integer(if_else(year<23, 2000+year, 1900+year))) %>%  
  subset(select = -day)%>% 
  arrange(year, month) %>% 
  subset(select = c(2,1,3))
```

``` r
unemployment_df = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv", show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_rate"
  ) %>% 
  mutate(
    year = as.integer(year),
    month = recode(month, "jan" = "Jan", "feb" = "Feb", "mar" = "Mar", "apr" = "Apr", "may"= "May", "jun" = "Jun", "jul" = "Jul", "aug" = "Aug" , "sep" = "Sep", "oct"="Oct", "nov" = "Nov", "dec" = "Dec")
    
  ) %>% 
  arrange(year, month)
```

``` r
pols_snp_combined_df = left_join(pols_df, snp_df)
```

    ## Joining, by = c("year", "month")

``` r
pols_snp_unemploy_combined_df = left_join(pols_snp_combined_df, unemployment_df)
```

    ## Joining, by = c("year", "month")

### Describing the 3 datasets and the combined datasets

The pols-month dataset contains information about politicians and
whether they are republican or democratic at a given time. The resulting
dataset after cleaning separates the date into separate day, month, and
year columns. Additionally, a new variable ‘president’ was created to
indicate if the president at that certain time period was a democrat or
a republican. Some columns that were redundant were dropped from the
dataset. There are 9 variables and 822 observations in this dataset. The
years in this dataset range from 1947 to 2015

The snp dataset contains information on closing prices for the S&P index
at a given point in time. The cleaned dataset is also broken out into
day, month, and year. This dataset has 3 variables and 787 observations.
The years in this dataset range from 1950 to 2015

Lastly, the unemployment dataset initially contained a year column and a
column for each month of the year. The observations were the
unemployment rate for that particular month/year combination. After
cleaning the dataset, the data was made longer and the separate month
columns were collapsed into one ‘month’ column. The resulting dataset
contains year, month, and the unemployment rate. This dataset has 3
variables and 816 observations. The years in this dataset range from
1948 to 2015.

The merging of the 3 datasets essentially gives information about how
the economy fared based on who was president and which party ruled the
house and senate. The resulting merged dataset has 11 variables and 822
observations. The years in this combined dataset range from 1947 to
2015. The key variables in this dataset are year/month, whether the
president at the time was a republican or a democrat, the snp closing
value and the unemployment rate during that month and year.
