---
title: "p8105_hw2_hbm2126"
output: github_document
date: "2022-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```


Problem 1

```{r importing, cleaning, and manipulating data}
subway_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c"), show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  select(line:entry, vending, ada) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

```{r}
subway_df %>% 
  select(station_name, line) %>% 
  distinct
```

```{r}
subway_df %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

```{r}
subway_df %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```


```{r}
subway_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct

subway_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

```{r, eval=FALSE}
View(subway_df)
```

Problem 2

```{r}
mr_trash_wheel_df= 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>%
  select(dumpster:homes_powered) %>%
  drop_na(dumpster) %>% 
  mutate(what_sheet = "Mr Trash Wheel") %>% 
  mutate(sports_balls = as.integer(round(sports_balls,0)))
  


```
```{r}
prof_trash_wheel_df= 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>%
  mutate(what_sheet = "Prof Trash Wheel") %>% 
  drop_na(dumpster)
  
```

```{r}
prof_trash_wheel_df$year = as.character(prof_trash_wheel_df$year)
```

```{r}
combined_trash_df = bind_rows(mr_trash_wheel_df, prof_trash_wheel_df)
```

```{r}
combined_trash_df %>% 
  filter(what_sheet == "Prof Trash Wheel") %>% 
  summarise(total_weight = sum(weight_tons))
  
```

```{r}
combined_trash_df %>% 
  filter(what_sheet == "Mr Trash Wheel" & year == 2020) %>% 
  summarise(total_sports_balls = sum(sports_balls))
```


Problem 3


```{r}
pols_df = 
  read_csv("data/fivethirtyeight_datasets/pols-month.csv", show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-")%>%
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day), 
    month = month.abb[month], 
    president = case_when(prez_gop == 1 ~ "gop", prez_dem == 1 ~ "dem")) %>% 
  subset(select = -c(day, prez_gop, prez_dem ))
```

```{r}
snp_df = 
  read_csv("data/fivethirtyeight_datasets/snp.csv", show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/")%>%
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    month = month.abb[month],
    year = as.integer(if_else(year<23, 2000+year, 1900+year))) %>%  
  subset(select = -day)%>% 
  arrange(year, month) %>% 
  subset(select = c(2,1,3))
  
```

```{r}
unemployment_df = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv", show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_rate"
  ) %>% 
  mutate(
    year = as.integer(year),
    month = recode(month, "jan" = "Jan", "feb" = "Feb", "mar" = "Mar", "apr" = "Apr", "may"= "May", "jun" = "Jun", "jul" = "Jul", "aug" = "Aug" , "sep" = "Sep", "oct"="Oct", "nov" = "Nov", "dec" = "Dec")
    
  ) %>% 
  arrange(year, month)
```

```{r}
pols_snp_combined_df = left_join(pols_df, snp_df)
pols_snp_unemploy_combined_df = left_join(pols_snp_combined_df, unemployment_df)


```


